Repository skalenetwork/docs.skale.space, pull requests merged in 2024-07, with the labels that each got.

#97 feat(Builders): Add Builders Section
  astro.config.mjs
  src/config/navigation.ts
  src/content/docs/builders/app-developers/overview.mdx
  src/content/docs/builders/chain-operators/overview.mdx
  src/content/docs/builders/index.mdx
  src/content/docs/builders/integration-guide.mdx
  src/content/docs/builders/node-operators/overview.mdx
  src/content/docs/developers/index.md
Labels: documentation, enhancement, ui/ux, ecosystem

#103 feat(Chain Operator): Migration & Upgrade Documentation
  astro.config.mjs
  package-lock.json
  package.json
  src/assets/skale_logo_b.svg
  src/assets/skale_logo_w.svg
  src/assets/skale_token_w.svg
  src/components/GasAndTokens/GasAndTokens.tsx
  src/components/Mermaid.astro
  src/components/Overrides/Header.astro
  src/components/Overrides/MobileMenuFooter.astro
  src/components/Overrides/PageFrame.astro
  src/components/Overrides/Sidebar.astro
  src/content/docs/builders/chain-operators/access-control.mdx
  src/content/docs/builders/chain-operators/administrative-contracts.mdx
  src/content/docs/builders/chain-operators/architecture.mdx
  src/content/docs/builders/chain-operators/best-practices.mdx
  src/content/docs/builders/chain-operators/multisig.mdx
  src/content/docs/builders/chain-operators/overview.mdx
  src/content/docs/builders/chain-operators/skale-chain-wallet.mdx
  src/content/docs/builders/chain-operators/submit-metadata.mdx
  src/content/docs/index.mdx
  src/styles/overrides.css
  tsconfig.json
Labels: documentation, enhancement, ecosystem

#108 cleanup(Styles): Cleanup Styles
  src/components/ChainDetails/ChainDetails.tsx
  src/components/GasAndTokens/GasAndTokens.tsx
  src/components/SelectChain/SelectChain.tsx
  src/config/chains.ts
  src/content/docs/index.mdx
  src/content/docs/quick-start/build.mdx
  src/content/docs/quick-start/building-for-skale.mdx
  src/content/docs/quick-start/deploy-to-testnet.mdx
  src/content/docs/quick-start/go-live.mdx
  src/content/docs/quick-start/index.mdx
  src/content/docs/quick-start/select-a-chain.mdx
  src/styles/overrides.css
Labels: bug, documentation, enhancement, ui/ux

#110 cleanup(Tools links): Clean broken links & updated card links
  astro.config.mjs
  src/components/NavigationItem.astro
  src/content/docs/builders/app-developers/sfuel-distribution/index.mdx
  src/content/docs/builders/tools/bridges/index.mdx
  src/content/docs/builders/tools/bridges/skale-native-bridge.mdx
  src/content/docs/builders/tools/contracts/index.mdx
  src/content/docs/builders/tools/data/index.mdx
  src/content/docs/builders/tools/gaming/index.mdx
  src/content/docs/builders/tools/index.mdx
  src/content/docs/builders/tools/libraries/index.mdx
  src/content/docs/builders/tools/nfts/index.mdx
  src/content/docs/builders/tools/nfts/marketplaces.mdx
  src/content/docs/builders/tools/nfts/marketplaces/keepsake.mdx
  src/content/docs/builders/tools/nfts/marketplaces/pixelrealm.mdx
  src/content/docs/builders/tools/nfts/nft-api.mdx
  src/content/docs/builders/tools/oracles/index.mdx
  src/content/docs/builders/tools/payments/index.mdx
  src/content/docs/builders/tools/wallets/aggregator.mdx
  src/content/docs/builders/tools/wallets/index.mdx
Labels: bug, documentation, enhancement

#112 bug(Pagefind): Fix Searchbar on Vercel Linux-64 Build
  package-lock.json
  package.json
Labels: bug

#111 feat(Builders): Add tools content + add steps as listing default
  astro.config.mjs
  package-lock.json
  package.json
  src/assets/openzeppelin-wizard.png
  src/assets/remix-compile.png
  src/assets/remix-deploy.png
  src/assets/remix-dply-btn.png
  src/content/docs/builders/app-developers/sfuel-distribution/api-distribution.mdx
  src/content/docs/builders/app-developers/sfuel-distribution/pow_examples/pow_csharp.mdx
  src/content/docs/builders/app-developers/sfuel-distribution/pow_examples/pow_dart.mdx
  src/content/docs/builders/app-developers/sfuel-distribution/pow_examples/pow_javascript.mdx
  src/content/docs/builders/app-developers/sfuel-distribution/pow_examples/pow_typescript.mdx
  src/content/docs/builders/chain-operators/submit-metadata.mdx
  src/content/docs/builders/node-operators/archive-node.mdx
  src/content/docs/builders/node-operators/full-sync-node.mdx
  src/content/docs/builders/node-operators/overview.mdx
  src/content/docs/builders/tools/bridges/layer-zero.mdx
  src/content/docs/builders/tools/contracts/hardhat.mdx
  src/content/docs/builders/tools/contracts/index.mdx
  src/content/docs/builders/tools/contracts/openzeppelin.mdx
  src/content/docs/builders/tools/contracts/remix.mdx
  src/content/docs/builders/tools/data/the-graph.mdx
  src/content/docs/builders/tools/gaming/eidolon.mdx
  src/content/docs/builders/tools/gaming/emergence.mdx
  src/content/docs/builders/tools/gaming/mirage.mdx
  src/content/docs/builders/tools/libraries/backend/kethereum.mdx
  src/content/docs/builders/tools/libraries/backend/web3j.mdx
  src/content/docs/builders/tools/libraries/json-rpc-calls.mdx
  src/content/docs/builders/tools/libraries/mobile/web3dart.mdx
  src/content/docs/builders/tools/libraries/web/ethersv5.mdx
  src/content/docs/builders/tools/libraries/web/ethersv6.mdx
  src/content/docs/builders/tools/libraries/web/viem.mdx
  src/content/docs/builders/tools/libraries/web/web3js.mdx
  src/content/docs/builders/tools/oracles/skale-connect.mdx
  src/content/docs/builders/tools/wallets/aggregator.mdx
  src/content/docs/builders/tools/wallets/aggregator/rainbowkit.mdx
  src/content/docs/builders/tools/wallets/aggregator/wallet-connect.mdx
  src/content/docs/builders/tools/wallets/custodial/invisible-signer.mdx
  src/content/docs/builders/tools/wallets/custodial/stardust.mdx
  src/content/docs/builders/tools/wallets/mpc/thirdweb.mdx
  src/content/docs/builders/tools/wallets/mpc/web3auth.mdx
  src/content/docs/builders/tools/wallets/non-custodial/bitski.mdx
  src/content/docs/builders/tools/wallets/non-custodial/coinbase.mdx
  src/content/docs/builders/tools/wallets/non-custodial/ledger.mdx
  src/content/docs/builders/tools/wallets/non-custodial/metamask.mdx
  src/content/docs/builders/tools/wallets/non-custodial/portis.mdx
  src/content/docs/builders/tools/wallets/non-custodial/trezor.mdx
  src/styles/overrides.css
Labels: bug, documentation, enhancement
